services:
  # Init container that just creates the ./clawp_files directory if it doesn't
  # exist. Necessary because the mount via the top-level volumes element doesn't
  # do this automatically.
  init-data-directory:
    image: "alpine:latest"
    volumes:
      - "./clawp_files:/app/clawp_files/"
    command: "chown 2000:2000 /app/clawp_files && chmod 711 /app/clawp_files"

  # Init container that generates SSH keys to be used in the shell sandbox.
  shell-sandbox-init:
    build:
      context: "shell_sandbox"
    command: "sh /scripts/generate_keys.sh"
    volumes:
      - "./shell_sandbox/generate_keys.sh:/scripts/generate_keys.sh:ro"
      - "sandbox-ssh-keys:/shared_ssh"

  # Ubuntu container acting as a sandbox for agent shell execution.
  shell-sandbox:
    build:
      context: "shell_sandbox"
    volumes:
      - "clawp-data:/app/clawp_files/"
      - type: "volume"
        source: "sandbox-ssh-keys"
        volume:
          subpath: "authorized_keys"
        target: "/root/.ssh/authorized_keys"
        read_only: true
    depends_on:
      init-data-directory:
        condition: "service_completed_successfully"
      shell-sandbox-init:
        condition: "service_completed_successfully"

  # The backend gateway.
  gateway:
    build:
      context: "gateway"
      target: "app"
    command: "clawp"
    volumes:
      - "./config.yaml:/app/config.yaml"
      - "clawp-data:/app/clawp_files/"
      - type: "volume"
        source: "sandbox-ssh-keys"
        volume:
          subpath: "id_shell_sandbox"
        target: "/app/clawp_files/shell_sandbox/id_shell_sandbox"
        read_only: true
    environment:
      - "CLAWP_OPENROUTER_API_KEY"
      - "CLAWP_MATRIX_PASSWORD_0"
    ports:
      - "8000:8000"
    depends_on:
      shell-sandbox:
        condition: "service_started"

volumes:
  # Volume containing persistent data like agents and config.
  clawp-data:
    driver: local
    driver_opts:
      type: "none"
      # We set the nosuid option, which disallows agents from setting the SGID
      # bit on files they create via the shell in the sandbox. This would be a
      # vulnerability, since they'd be able to execute scripts with the
      # permissions of the clawp group, which has access to anything in the data
      # directory.
      o: "bind,nosuid"
      device: "${PWD}/clawp_files/"
  # Volume to write the sandbox SSH key into.
  sandbox-ssh-keys:
