services:
  gateway:
    build:
      context: "gateway"
      target: "app"
    command: "clawp"
    volumes:
      - "./config.yaml:/app/config.yaml"
      - "./clawp_files/:/app/clawp_files/"
    environment:
      - "CLAWP_OPENROUTER_API_KEY"
      - "CLAWP_MATRIX_PASSWORD_0"
    ports:
      - "8000:8000"
