name: "test"

on:
  push:
    branches-ignore:
      - "stash"
      - "stash/**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v7"
      - name: "Build CI image"
        run: "docker compose -f docker-compose.test.yaml build test"
      - name: "Run tests"
        run: "docker compose -f docker-compose.test.yaml run --rm --no-deps test"
      - name: "Run BasedPyright"
        run: "docker compose -f docker-compose.test.yaml run --rm --no-deps basedpyright"
      - name: "Run Ruff"
        run: "docker compose -f docker-compose.test.yaml run --rm --no-deps ruff"
      - name: "Clean up"
        if: "${{ always() }}"
        run: "docker compose -f docker-compose.test.yaml down"
