name: test

on:
  push:
    branches-ignore:
      - "stash"
      - "stash/**"
    tags-ignore:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run tests
        run: docker compose -f docker-compose.test.yaml up --build --exit-code-from=test
      - name: Clean up
        if: ${{ always() }}
        run: docker compose -f docker-compose.test.yaml down
