server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        # Set the resolver to the docker-compose specific resolver with a cache
        # time of 10s and 2s timeout.
        resolver 127.0.0.11 valid=10s ipv6=off;
        resolver_timeout 2s;

        # Set the gateway address as a variable. This gets nginx to resolve it
        # on demand rather than on startup. If we specify proxy_pass directly,
        # it  will crash on startup if the gateway isn't available yet. We can't
        # specify a depends_on on the compose file to force nginx to start after
        # the gateway, since that means the gateway also gets SITGERMed after
        # nginx, making a clean shutdown of open connections impossible.
        set $gateway_upstream gateway:8000;
        proxy_pass http://$gateway_upstream;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
